In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv


In [2]:
df=pd.read_csv('/kaggle/input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df.corr(method='pearson')

SeniorCitizen    tenure  MonthlyCharges
SeniorCitizen        1.000000  0.016567        0.220173
tenure               0.016567  1.000000        0.247900
MonthlyCharges       0.220173  0.247900        1.000000

In [4]:
df['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [5]:
X=df.drop(['customerID','Churn'],axis=1)

In [6]:
y=df['Churn']

In [7]:
X.info

<bound method DataFrame.info of       gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

         MultipleLines InternetService OnlineSecurity OnlineBackup  \
0     No phone service             DSL       

In [8]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)

In [9]:
X.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [10]:
X=pd.get_dummies(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [12]:
from sklearn.linear_model import LogisticRegression
d=LogisticRegression()
d.fit(X_train,y_train)
d.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8126330731014905

In [13]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier()
k.fit(X_train,y_train)
k.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.7806955287437899

In [14]:
from sklearn.svm import SVC
w=SVC()
w.fit(X_train,y_train)
w.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.7977288857345636

In [15]:
from sklearn.naive_bayes import GaussianNB
u=GaussianNB()
u.fit(X_train,y_train)
u.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.276792051100071

In [16]:
from sklearn.tree import DecisionTreeClassifier
m=DecisionTreeClassifier()
m.fit(X_train,y_train)
m.score(X_test,y_test)

0.7913413768630234

In [17]:
from sklearn.ensemble import RandomForestClassifier
o=RandomForestClassifier()
o.fit(X_train,y_train)
o.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.8041163946061036

In [18]:
from sklearn.ensemble import ExtraTreesClassifier
i=ExtraTreesClassifier()
i.fit(X_train,y_train)
i.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.7806955287437899

In [19]:
from sklearn.linear_model import SGDClassifier
r=SGDClassifier()
r.fit(X_train,y_train)
r.score(X_test,y_test)

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7551454932576295

In [20]:
from sklearn.metrics import confusion_matrix
y_predict=d.predict(X_test)
results=confusion_matrix(y_test,y_predict)
print("confusion_matrix")
print(results)


confusion_matrix
[[947  95]
 [169 198]]


In [21]:
# save model
import pickle
file_names="churn.sav"
tuples=(d,X)
pickle.dump(tuples,open(file_names,'wb'))

In [22]:
from sklearn.metrics import confusion_matrix
y_predict1=k.predict(X_test)
results1=confusion_matrix(y_test,y_predict1)
print("confusion_matrix")
print(results1)

confusion_matrix
[[916 126]
 [183 184]]


In [23]:
from sklearn.metrics import confusion_matrix
y_predict2=w.predict(X_test)
results2=confusion_matrix(y_test,y_predict2)
print("confusion_matrix")
print(results2)

confusion_matrix
[[970  72]
 [213 154]]


In [24]:
from sklearn.metrics import confusion_matrix
y_predict3=m.predict(X_test)
results3=confusion_matrix(y_test,y_predict3)
print("confusion_matrix")
print(results3)

confusion_matrix
[[919 123]
 [171 196]]


In [25]:
from sklearn.metrics import confusion_matrix
y_predict4=u.predict(X_test)
results4=confusion_matrix(y_test,y_predict4)
print("confusion_matrix")
print(results4)

confusion_matrix
[[ 48 994]
 [ 25 342]]


In [26]:
from sklearn.metrics import confusion_matrix
y_predict5=r.predict(X_test)
results5=confusion_matrix(y_test,y_predict5)
print("confusion_matrix")
print(results5)

confusion_matrix
[[1036    6]
 [ 339   28]]


In [27]:
from sklearn.metrics import roc_curve,auc,roc_auc_score
fpr,tpr,threshold=roc_curve(y_test,k.predict_proba(X_test)[:,1])
print(fpr,'',tpr,'',threshold)


[0.         0.01247601 0.04798464 0.12092131 0.27351248 0.49616123
 1.        ]  [0.         0.14713896 0.32425068 0.5013624  0.73024523 0.89918256
 1.        ]  [2.  1.  0.8 0.6 0.4 0.2 0. ]


In [28]:
from sklearn.metrics import roc_curve,auc,roc_auc_score
fpr1,tpr1,threshold1=roc_curve(y_test,d.predict_proba(X_test)[:,1])
print(fpr1,'',tpr1,'',threshold1)

[0.00000000e+00 0.00000000e+00 0.00000000e+00 9.59692898e-04
 9.59692898e-04 1.91938580e-03 1.91938580e-03 2.87907869e-03
 2.87907869e-03 3.83877159e-03 3.83877159e-03 5.75815739e-03
 5.75815739e-03 6.71785029e-03 6.71785029e-03 7.67754319e-03
 7.67754319e-03 8.63723608e-03 8.63723608e-03 9.59692898e-03
 9.59692898e-03 1.05566219e-02 1.05566219e-02 1.15163148e-02
 1.15163148e-02 1.24760077e-02 1.24760077e-02 1.34357006e-02
 1.34357006e-02 1.53550864e-02 1.53550864e-02 1.72744722e-02
 1.72744722e-02 1.82341651e-02 1.82341651e-02 1.91938580e-02
 1.91938580e-02 2.01535509e-02 2.01535509e-02 2.11132438e-02
 2.11132438e-02 2.20729367e-02 2.20729367e-02 2.30326296e-02
 2.39923225e-02 2.49520154e-02 2.49520154e-02 2.59117083e-02
 2.59117083e-02 2.68714012e-02 2.68714012e-02 2.87907869e-02
 2.87907869e-02 3.07101727e-02 3.07101727e-02 3.26295585e-02
 3.26295585e-02 3.35892514e-02 3.35892514e-02 3.74280230e-02
 3.74280230e-02 3.93474088e-02 3.93474088e-02 4.03071017e-02
 4.03071017e-02 4.222648

In [29]:
from sklearn.metrics import roc_curve,auc,roc_auc_score
fpr2,tpr2,threshold2=roc_curve(y_test,m.predict_proba(X_test)[:,1])
print(fpr2,'',tpr2,'',threshold2)

[0.         0.11804223 0.11900192 1.        ]  [0.         0.53405995 0.54223433 1.        ]  [2.  1.  0.5 0. ]


In [30]:
from sklearn.metrics import roc_curve,auc,roc_auc_score
fpr3,tpr3,threshold3=roc_curve(y_test,u.predict_proba(X_test)[:,1])
print(fpr3,'',tpr3,'',threshold3)

[0.         0.95393474 1.        ]  [0.         0.93188011 1.        ]  [2. 1. 0.]


In [31]:
roc_auc=roc_auc_score(y_test,k.predict(X_test))
roc_auc

0.6902205463189108

In [32]:
roc_auc1=roc_auc_score(y_test,d.predict(X_test))
roc_auc1

0.7241693557244243

In [33]:
roc_auc2=roc_auc_score(y_test,m.predict(X_test))
roc_auc2

0.7080088595082815

In [34]:
roc_auc3=roc_auc_score(y_test,u.predict(X_test))
roc_auc3

0.48897268405445404

In [35]:
yfg=d.predict_proba(X_test)

In [36]:
yfg

array([[0.86961413, 0.13038587],
       [0.5148024 , 0.4851976 ],
       [0.98284346, 0.01715654],
       ...,
       [0.70169616, 0.29830384],
       [0.79342164, 0.20657836],
       [0.5875533 , 0.4124467 ]])

In [37]:
from sklearn.preprocessing import binarize
yqc=binarize(yfg,0.60)
yqc[:]

array([[1., 0.],
       [0., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 0.]])

In [38]:
rt=yqc[:,1]

In [39]:
fb=rt.astype(int)

In [40]:
from sklearn.metrics import confusion_matrix
hj=confusion_matrix(y_test,fb)
hj

array([[989,  53],
       [224, 143]])

In [41]:
from sklearn.preprocessing import binarize
yqc=binarize(yfg,0.70)
yqc[:]
rt=yqc[:,1]
fb=rt.astype(int)
from sklearn.metrics import confusion_matrix
hj=confusion_matrix(y_test,fb)
hj

array([[1023,   19],
       [ 283,   84]])

In [42]:
from sklearn.preprocessing import binarize
yqc=binarize(yfg,0.80)
yqc[:]
rt=yqc[:,1]
fb=rt.astype(int)
from sklearn.metrics import confusion_matrix
hj=confusion_matrix(y_test,fb)
hj

array([[1038,    4],
       [ 346,   21]])

In [43]:
from sklearn.preprocessing import binarize
yqc=binarize(yfg,0.90)
yqc[:]
rt=yqc[:,1]
fb=rt.astype(int)
from sklearn.metrics import confusion_matrix
hj=confusion_matrix(y_test,fb)
hj

array([[1042,    0],
       [ 367,    0]])