In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/heart-disease-uci/heart.csv


In [2]:
data=pd.read_csv("../input/heart-disease-uci/heart.csv")
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
%matplotlib inline
import seaborn as sns

In [4]:
x=data.iloc[:,0:13]
y=data.iloc[:,13:]

In [5]:
from sklearn.model_selection import cross_val_score
from catboost import CatBoostClassifier
cat=CatBoostClassifier(iterations=5)
cross_val_score(cat,x,y,cv=3)

Learning rate set to 0.5
0:	learn: 0.6026946	total: 53.3ms	remaining: 213ms
1:	learn: 0.5005685	total: 54.6ms	remaining: 81.9ms
2:	learn: 0.4543639	total: 55.7ms	remaining: 37.1ms
3:	learn: 0.4164360	total: 56.7ms	remaining: 14.2ms
4:	learn: 0.3865602	total: 57.7ms	remaining: 0us
Learning rate set to 0.5
0:	learn: 0.5952476	total: 1.37ms	remaining: 5.49ms
1:	learn: 0.4997867	total: 2.87ms	remaining: 4.3ms
2:	learn: 0.4552547	total: 4.15ms	remaining: 2.77ms
3:	learn: 0.4272284	total: 5.47ms	remaining: 1.37ms
4:	learn: 0.3945969	total: 6.97ms	remaining: 0us
Learning rate set to 0.5
0:	learn: 0.5579294	total: 718us	remaining: 2.87ms
1:	learn: 0.4705210	total: 1.9ms	remaining: 2.85ms
2:	learn: 0.4162723	total: 2.97ms	remaining: 1.98ms
3:	learn: 0.3773926	total: 4.12ms	remaining: 1.03ms
4:	learn: 0.3447337	total: 5.17ms	remaining: 0us


array([0.79207921, 0.87128713, 0.76237624])

## Catboost have promising results.

In [6]:
cat=CatBoostClassifier(iterations=50)
cross_val_score(cat,x,y,cv=3)

Learning rate set to 0.153729
0:	learn: 0.6633012	total: 1.19ms	remaining: 58.2ms
1:	learn: 0.6220204	total: 2.29ms	remaining: 55ms
2:	learn: 0.5974368	total: 3.4ms	remaining: 53.2ms
3:	learn: 0.5749036	total: 4.87ms	remaining: 56ms
4:	learn: 0.5534403	total: 5.89ms	remaining: 53.1ms
5:	learn: 0.5297457	total: 6.94ms	remaining: 50.9ms
6:	learn: 0.5056613	total: 8.02ms	remaining: 49.3ms
7:	learn: 0.4834170	total: 9.11ms	remaining: 47.8ms
8:	learn: 0.4709956	total: 10.1ms	remaining: 46ms
9:	learn: 0.4581387	total: 11.1ms	remaining: 44.4ms
10:	learn: 0.4451755	total: 12.1ms	remaining: 43ms
11:	learn: 0.4335307	total: 13.1ms	remaining: 41.6ms
12:	learn: 0.4220449	total: 14.1ms	remaining: 40.1ms
13:	learn: 0.4103191	total: 15.1ms	remaining: 38.7ms
14:	learn: 0.3999194	total: 16ms	remaining: 37.4ms
15:	learn: 0.3907005	total: 17ms	remaining: 36.2ms
16:	learn: 0.3822214	total: 18ms	remaining: 35ms
17:	learn: 0.3735879	total: 19ms	remaining: 33.7ms
18:	learn: 0.3670632	total: 20ms	remaining: 3

array([0.82178218, 0.85148515, 0.78217822])

### I don't know much about catboost but looks like it's work.

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [8]:
cat=CatBoostClassifier(iterations=150,learning_rate=1)
cat.fit(X_train,y_train)

0:	learn: 0.4869497	total: 1.42ms	remaining: 212ms
1:	learn: 0.3895800	total: 2.85ms	remaining: 211ms
2:	learn: 0.3496517	total: 4.14ms	remaining: 203ms
3:	learn: 0.3115664	total: 5.25ms	remaining: 192ms
4:	learn: 0.2850753	total: 6.53ms	remaining: 189ms
5:	learn: 0.2608714	total: 7.61ms	remaining: 183ms
6:	learn: 0.2374583	total: 8.76ms	remaining: 179ms
7:	learn: 0.2194163	total: 9.88ms	remaining: 175ms
8:	learn: 0.2028531	total: 11ms	remaining: 172ms
9:	learn: 0.1891470	total: 12.1ms	remaining: 169ms
10:	learn: 0.1792033	total: 13.2ms	remaining: 167ms
11:	learn: 0.1679953	total: 14.5ms	remaining: 167ms
12:	learn: 0.1589948	total: 15.7ms	remaining: 166ms
13:	learn: 0.1506493	total: 16.8ms	remaining: 164ms
14:	learn: 0.1383219	total: 17.9ms	remaining: 162ms
15:	learn: 0.1321145	total: 19.4ms	remaining: 163ms
16:	learn: 0.1236966	total: 20.5ms	remaining: 161ms
17:	learn: 0.1169977	total: 21.6ms	remaining: 158ms
18:	learn: 0.1082740	total: 22.6ms	remaining: 156ms
19:	learn: 0.1057151	tot

In [9]:
ypred=cat.predict(X_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.7894736842105263
[[27  8]
 [ 8 33]]


In [10]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=20)
gb.fit(X_train,y_train)
ypred=gb.predict(X_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8289473684210527
[[28  7]
 [ 6 35]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=10)
gb.fit(X_train,y_train)
ypred=gb.predict(X_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8421052631578947
[[28  7]
 [ 5 36]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## İt's work better than Catboost.What our old friend random forest. 

In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred=rfc.predict(X_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8552631578947368
[[31  4]
 [ 7 34]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


## Random forest is works better than XGBoost

In [13]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x_pca=pca.fit_transform(x)

In [14]:
from sklearn.model_selection import train_test_split
xp_train, xp_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.25, random_state=42)

In [15]:
cat=CatBoostClassifier(iterations=150,learning_rate=1)
cat.fit(xp_train,y_train)
ypred=cat.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0:	learn: 0.6153761	total: 1.91ms	remaining: 284ms
1:	learn: 0.5911315	total: 3.45ms	remaining: 255ms
2:	learn: 0.5414581	total: 5.04ms	remaining: 247ms
3:	learn: 0.5355082	total: 6.28ms	remaining: 229ms
4:	learn: 0.5152087	total: 7.51ms	remaining: 218ms
5:	learn: 0.5016776	total: 8.76ms	remaining: 210ms
6:	learn: 0.4845200	total: 10ms	remaining: 205ms
7:	learn: 0.4689587	total: 11.2ms	remaining: 199ms
8:	learn: 0.4476694	total: 12.5ms	remaining: 195ms
9:	learn: 0.4357007	total: 13.8ms	remaining: 193ms
10:	learn: 0.4145255	total: 15.1ms	remaining: 191ms
11:	learn: 0.3989594	total: 16.4ms	remaining: 188ms
12:	learn: 0.3857375	total: 17.7ms	remaining: 187ms
13:	learn: 0.3774088	total: 18.7ms	remaining: 181ms
14:	learn: 0.3654064	total: 19.8ms	remaining: 178ms
15:	learn: 0.3508953	total: 21ms	remaining: 176ms
16:	learn: 0.3341799	total: 22.2ms	remaining: 174ms
17:	learn: 0.3238512	total: 23.4ms	remaining: 172ms
18:	learn: 0.3089124	total: 24.6ms	remaining: 170ms
19:	learn: 0.3005638	total

Catboost is crying. %64 accuracy is horrific.

In [16]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=10)
gb.fit(xp_train,y_train)
ypred=gb.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.6710526315789473
[[20 15]
 [10 31]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xp_train,y_train)
ypred=rfc.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.631578947368421
[[24 11]
 [17 24]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


## Less column can't work well with these algorithm. Especially gradient boosting algorithm. 

In [18]:
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
x_pca=pca.fit_transform(x)

In [19]:
from sklearn.model_selection import train_test_split
xp_train, xp_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.25, random_state=42)


In [20]:
cat=CatBoostClassifier(iterations=150,learning_rate=1)
cat.fit(xp_train,y_train)
ypred=cat.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0:	learn: 0.5314373	total: 4.57ms	remaining: 680ms
1:	learn: 0.4164720	total: 7.26ms	remaining: 537ms
2:	learn: 0.3790486	total: 9.8ms	remaining: 480ms
3:	learn: 0.3410872	total: 12.1ms	remaining: 440ms
4:	learn: 0.3105262	total: 14.2ms	remaining: 413ms
5:	learn: 0.2786178	total: 16.5ms	remaining: 396ms
6:	learn: 0.2415711	total: 18.7ms	remaining: 381ms
7:	learn: 0.2208966	total: 20.9ms	remaining: 371ms
8:	learn: 0.2052018	total: 23.1ms	remaining: 362ms
9:	learn: 0.1955715	total: 25.5ms	remaining: 357ms
10:	learn: 0.1819924	total: 27.7ms	remaining: 350ms
11:	learn: 0.1684584	total: 29.9ms	remaining: 344ms
12:	learn: 0.1544622	total: 32.3ms	remaining: 340ms
13:	learn: 0.1397069	total: 34.7ms	remaining: 337ms
14:	learn: 0.1262503	total: 37.1ms	remaining: 334ms
15:	learn: 0.1219481	total: 39.5ms	remaining: 330ms
16:	learn: 0.1168237	total: 41.7ms	remaining: 326ms
17:	learn: 0.1117126	total: 43.9ms	remaining: 322ms
18:	learn: 0.1051212	total: 46.4ms	remaining: 320ms
19:	learn: 0.1006792	to

Better than 3 component pca but not best.

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=10)
gb.fit(xp_train,y_train)
ypred=gb.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.7368421052631579
[[26  9]
 [11 30]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Same things as catboost.

In [22]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xp_train,y_train)
ypred=rfc.predict(xp_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.6973684210526315
[[29  6]
 [17 24]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Same

## Conclusion
Boosting Algorithm has potential but old school algorithm is also in race. 

In [23]:
import category_encoders as ce
count_encode=ce.CountEncoder(cols=["sex","cp","slope","thal"])
x_count=count_encode.fit_transform(x)

from sklearn.model_selection import train_test_split
Xco_train, Xco_test, y_train, y_test = train_test_split(x_count, y, test_size=0.25, random_state=42)

In [24]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(Xco_train,y_train)
ypred=rfc.predict(Xco_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8552631578947368
[[31  4]
 [ 7 34]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [25]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=10)
gb.fit(Xco_train,y_train)
ypred=gb.predict(Xco_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8552631578947368
[[29  6]
 [ 5 36]]


/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


With Count Encoder accuracy is greater than ever. 

In [26]:
from sklearn.model_selection import cross_val_score
from catboost import CatBoostClassifier
cat=CatBoostClassifier(iterations=5)
cross_val_score(cat,x_count,y,cv=3)

Learning rate set to 0.5
0:	learn: 0.6026946	total: 1.15ms	remaining: 4.61ms
1:	learn: 0.5284926	total: 2.5ms	remaining: 3.75ms
2:	learn: 0.4700288	total: 3.61ms	remaining: 2.4ms
3:	learn: 0.4344300	total: 4.81ms	remaining: 1.2ms
4:	learn: 0.3989819	total: 5.83ms	remaining: 0us
Learning rate set to 0.5
0:	learn: 0.5952476	total: 1.11ms	remaining: 4.46ms
1:	learn: 0.4996570	total: 2.32ms	remaining: 3.48ms
2:	learn: 0.4484215	total: 3.45ms	remaining: 2.3ms
3:	learn: 0.4181829	total: 4.52ms	remaining: 1.13ms
4:	learn: 0.3822077	total: 5.62ms	remaining: 0us
Learning rate set to 0.5
0:	learn: 0.5650121	total: 1.24ms	remaining: 4.97ms
1:	learn: 0.4881137	total: 2.47ms	remaining: 3.71ms
2:	learn: 0.4396295	total: 3.63ms	remaining: 2.42ms
3:	learn: 0.4039478	total: 4.33ms	remaining: 1.08ms
4:	learn: 0.3742253	total: 5.37ms	remaining: 0us


array([0.83168317, 0.86138614, 0.78217822])

In [27]:
cat=CatBoostClassifier(verbose=0)
cat.fit(Xco_train,y_train)
ypred=cat.predict(Xco_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))

0.8421052631578947
[[29  6]
 [ 6 35]]


## Count Encoders improve Categorical variable further with frequency and it's works :)