In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/ph-recognition/ph-data.csv


In [2]:
data=pd.read_csv("/kaggle/input/ph-recognition/ph-data.csv")
data.head()

blue  green  red  label
0    36     27  231      0
1    36     84  250      1
2    37    164  255      2
3    22    205  255      3
4    38    223  221      4

In [3]:
x=data.iloc[:,0:3]
y=data.iloc[:,3:]

## I think, Decision Tree work best for this dataset.

In [4]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion= "entropy")

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [6]:
dtc.fit(x_train,y_train)
ypred=dtc.predict(x_test)
import sklearn.metrics as metrik
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))
print(metrik.classification_report(y_true=y_test,y_pred=ypred))

0.7195121951219512
[[ 8  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  2  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  7  2  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  1  1  8  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  7  0  1  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  2  9  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  4  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 10  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  1  9  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  5  1]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  1  3 14]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89         9
           1       0.82      0.82      0.82        11
           2       0.55      0.60      0.57        10
           3       0.64      0.50      0.56

## Accuracy is not good enough with Decision Tree

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scale_x=scaler.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(scale_x, y, test_size=0.25, random_state=42)

In [8]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(128, input_dim=3, kernel_initializer='normal', activation='relu'))
model.add(Dense(60,kernel_initializer='normal', activation='relu'))
model.add(Dense(15,kernel_initializer='normal', activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Using TensorFlow backend.
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

In [9]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
encoder = LabelEncoder()
encoder.fit(y)
encoded_Y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)
dummy_y

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(scale_x, dummy_y, test_size=0.25, random_state=42)

In [11]:
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
489/489 [==============================] - 0s 752us/step - loss: 2.6964 - acc: 0.1943
Epoch 2/200
489/489 [==============================] - 0s 52us/step - loss: 2.6404 - acc: 0.3006
Epoch 3/200
489/489 [==============================] - 0s 47us/step - loss: 2.4850 - acc: 0.2883
Epoch 4/200
489/489 [==============================] - 0s 58us/step - loss: 2.1960 - acc: 0.2883
Epoch 5/200
489/489 [==============================] - 0s 62us/step - loss: 1.9073 - acc: 0.2965
Epoch 6/200
489/489 [==============================] - 0s 57us/step - loss: 1.6701 - acc: 0.3763
Epoch 7/200
489/489 [==============================] - 0s 49us/step - loss: 1.5116 - acc: 0.4397
Epoch 8/200
489/489 [==============================] - 0s 48us/step - loss: 1.4084 - acc: 0.5665
Epoch 9/200
489/489 [==============================] - 0s 63us/step - loss: 1.3393 - acc: 0.5317
Epoch 10/200
489/489 [==============================] - 0s 48us/step - loss: 1.3011 - acc: 0.5706
Epoch 11/200
489/489 [======

## Can't work well either just %78

In [12]:
ypred2=model.predict(X_test)
ypred=ypred2.argmax(1)
y_test=y_test.argmax(1)
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))
print(metrik.classification_report(y_true=y_test,y_pred=ypred))

0.75
[[ 8  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  5  8  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  2  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  1  8  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  3  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  3  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  2  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 10  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  3  0  1  9  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1  7  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  3 15]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89         9
           1       0.83      0.91      0.87        11
           2       0.53      1.00      0.69        10
           3       0.67      0.57      0.62        14
   

## Can't work good enough. İnterestingly. Add more layers maybe work better.

In [13]:
model = Sequential()
model.add(Dense(1024, input_dim=3, kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dense(120,kernel_initializer='normal', activation='relu'))
model.add(Dense(60,kernel_initializer='normal', activation='relu'))
model.add(Dense(15,kernel_initializer='normal', activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
X_train, X_test, y2_train, y2_test = train_test_split(scale_x, dummy_y, test_size=0.25, random_state=42)
model.fit(X_train,y2_train,epochs=200)

Epoch 1/200
489/489 [==============================] - 1s 1ms/step - loss: 2.6025 - acc: 0.3088
Epoch 2/200
489/489 [==============================] - 0s 314us/step - loss: 1.8197 - acc: 0.3988
Epoch 3/200
489/489 [==============================] - 0s 331us/step - loss: 1.3451 - acc: 0.4847
Epoch 4/200
489/489 [==============================] - 0s 321us/step - loss: 1.2656 - acc: 0.5051
Epoch 5/200
489/489 [==============================] - 0s 305us/step - loss: 1.2136 - acc: 0.5337
Epoch 6/200
489/489 [==============================] - 0s 321us/step - loss: 1.1655 - acc: 0.5992
Epoch 7/200
489/489 [==============================] - 0s 321us/step - loss: 1.1069 - acc: 0.6278
Epoch 8/200
489/489 [==============================] - 0s 309us/step - loss: 1.0912 - acc: 0.6053
Epoch 9/200
489/489 [==============================] - 0s 324us/step - loss: 1.0785 - acc: 0.6155
Epoch 10/200
489/489 [==============================] - 0s 303us/step - loss: 1.0262 - acc: 0.6319
Epoch 11/200
489/489 

In [15]:
ypred3=model.predict(X_test)
ypred=ypred3.argmax(1)
y_test=y2_test.argmax(1)
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))
print(metrik.classification_report(y_true=y_test,y_pred=ypred))

0.7317073170731707
[[ 8  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  9  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  6  3  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  2 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  3  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  0  3  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1 10  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 10  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  2  0  2  9  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  6  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  5 11]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.90      0.82      0.86        11
           2       0.56      0.90      0.69        10
           3       0.90      0.64      0.75

Test performance is not good. Deep NN can't work best for these dataset.

Maybe KNN is worked just fine. Distance based Algorithm work well in this type of situation. 

In [16]:
print(data.shape)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

(653, 4)


In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)
knn.fit(x_train,y_train)
ypred=knn.predict(x_test)
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))
print(metrik.classification_report(y_true=y_test,y_pred=ypred))

0.7073170731707317
[[ 8  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  9  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  6  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  3  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  1  8  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  2  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  3  1  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  2  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  1  0  1  0  0]
 [ 0  0  0  0  0  0  0  1  0  0 10  0  0  1  0]
 [ 0  0  0  0  0  0  0  1  2  0  1  9  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  6  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  3  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  2 16]]
              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.77      0.91      0.83        11
           2       0.50      0.90      0.64        10
           3       0.55      0.43      0.48

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


İnterestingly interesting.

In [18]:
best=0
best_acc=0
for i in range(1,15):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    ypred=knn.predict(x_test)
    acc=metrik.accuracy_score(y_true=y_test,y_pred=ypred)
    if best_acc<acc:
        best=i
        best_acc=acc
print("Accuracy: "+str(best_acc))
print("neighbour: "+str(best))

Accuracy: 0.7560975609756098
neighbour: 1


/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-

Best is %75 with KNN or 1NN

Maybe our classes is too many. Many use only 0 or 1 0 asidic 1 basic.

In [19]:
ybinary=y>7
ybinary=ybinary.astype(int)

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, ybinary, test_size=0.25, random_state=42)
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)
ypred=knn.predict(x_test)
print(metrik.accuracy_score(y_true=y_test,y_pred=ypred))
print(metrik.confusion_matrix(y_true=y_test,y_pred=ypred))
print(metrik.classification_report(y_true=y_test,y_pred=ypred))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.975609756097561
[[83  2]
 [ 2 77]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        85
           1       0.97      0.97      0.97        79

    accuracy                           0.98       164
   macro avg       0.98      0.98      0.98       164
weighted avg       0.98      0.98      0.98       164



These APPROACH work just fine. Howewer we forget notr in this time :)