In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('../input/bank-churn-modelling/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = df.iloc[:, 6:13].values
y = df.iloc[:, 13].values

In [5]:
print(X)

[[4.2000000e+01 2.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [4.1000000e+01 1.0000000e+00 8.3807860e+04 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [4.2000000e+01 8.0000000e+00 1.5966080e+05 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [3.6000000e+01 7.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [4.2000000e+01 3.0000000e+00 7.5075310e+04 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [2.8000000e+01 4.0000000e+00 1.3014279e+05 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

****K-NEAREST NEIGHBORS****

In [9]:
# Fitting K Nearest Neighbor Classification to the Training Set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)  #ดู K=5, มิติ P=2 คือ euclidean space
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
y_pred = classifier.predict(X_test)

In [11]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) #บ่งบอกว่า testดีหรือไม่ดี true pos,true neg. ควรสูง , False pos.,False neg ควรต่ำ
print(cm)

[[1878  113]
 [ 279  230]]


In [12]:
# Visualising the Training set results

from  matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape), 
             alpha = 0.75, cmap = ListedColormap(('YELLOW', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)): 
    plt.scatter(X_set[y_set == j,0],X_set[y_set == j,1], 
                c = ListedColormap(('red','pink'))(i), label = j)
plt.title('KNN (Training set)')
plt.xlabel('CreditScore')
plt.ylabel('EstimatedSalary')
plt.legend()
plt.show()

ValueError: query data dimension must match training data dimension

****SVM****

In [13]:
# Fitting SVM to the Training Set
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', degree = 2, random_state = 0) #degree for non-linear
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) #บ่งบอกว่า testดีหรือไม่ดี true pos,true neg. ควรสูง , False pos.,False neg ควรต่ำ
print(cm)

[[1979   12]
 [ 438   71]]


In [16]:
# Visualising the Training set results

from  matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape), 
             alpha = 0.75, cmap = ListedColormap(('YELLOW', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)): 
    plt.scatter(X_set[y_set == j,0],X_set[y_set == j,1], 
                c = ListedColormap(('red','pink'))(i), label = j)
plt.title('KNN (Training set)')
plt.xlabel('CreditScore')
plt.ylabel('EstimatedSalary')
plt.legend()
plt.show()

ValueError: X.shape[1] = 2 should be equal to 7, the number of features at training time

**NAÏVE	BAYES**

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) #บ่งบอกว่า testดีหรือไม่ดี true pos,true neg. ควรสูง , False pos.,False neg ควรต่ำ
print(cm)

[[1945   46]
 [ 390  119]]


In [20]:
# Visualising the Training set results

from  matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape), 
             alpha = 0.75, cmap = ListedColormap(('YELLOW', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)): 
    plt.scatter(X_set[y_set == j,0],X_set[y_set == j,1], 
                c = ListedColormap(('red','pink'))(i), label = j)
plt.title('KNN (Training set)')
plt.xlabel('CreditScore')
plt.ylabel('EstimatedSalary')
plt.legend()
plt.show()

ValueError: operands could not be broadcast together with shapes (459480,2) (7,) 