In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['heart.csv']


In [2]:
data = pd.read_csv('../input/heart.csv')
data.head()

age  sex  cp  trestbps  chol   ...    oldpeak  slope  ca  thal  target
0   63    1   3       145   233   ...        2.3      0   0     1       1
1   37    1   2       130   250   ...        3.5      0   0     2       1
2   41    0   1       130   204   ...        1.4      2   0     2       1
3   56    1   1       120   236   ...        0.8      2   0     2       1
4   57    0   0       120   354   ...        0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [4]:
feature_col =['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
#Input variables
X = data.loc[:,feature_col]
X= preprocessing.scale(np.array(X))
#Output variables
y = data['target']

In [5]:
# Splitting the data in train test
x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.35)

In [6]:
# Model Selection Naive Bayes

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB().fit(x_train,y_train)
predict = gnb.predict(x_test)

print(accuracy_score(predict,y_test))
print(confusion_matrix(predict,y_test))
print(classification_report(predict,y_test))

0.8317757009345794
[[38 12]
 [ 6 51]]
              precision    recall  f1-score   support

           0       0.86      0.76      0.81        50
           1       0.81      0.89      0.85        57

   micro avg       0.83      0.83      0.83       107
   macro avg       0.84      0.83      0.83       107
weighted avg       0.83      0.83      0.83       107



In [7]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression().fit(x_train,y_train)
predict_lr = gnb.predict(x_test)

print(accuracy_score(predict_lr,y_test))
print(confusion_matrix(predict_lr,y_test))
print(classification_report(predict_lr,y_test))

0.8317757009345794
[[38 12]
 [ 6 51]]
              precision    recall  f1-score   support

           0       0.86      0.76      0.81        50
           1       0.81      0.89      0.85        57

   micro avg       0.83      0.83      0.83       107
   macro avg       0.84      0.83      0.83       107
weighted avg       0.83      0.83      0.83       107



/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [8]:
from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(n_neighbors=10).fit(x_train,y_train)
predict_knc = gnb.predict(x_test)

print(accuracy_score(predict_knc,y_test))
print(confusion_matrix(predict_knc,y_test))



0.8317757009345794
[[38 12]
 [ 6 51]]


In [9]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=25).fit(x_train,y_train)
predict_rfc = rfc.predict(x_test)

print(accuracy_score(predict_rfc,y_test))
print(confusion_matrix(predict_rfc,y_test))


0.8411214953271028
[[36  9]
 [ 8 54]]
