In [112]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/habermans-survival-data-set/haberman.csv


In [113]:
haberman=pd.read_csv('../input/habermans-survival-data-set/haberman.csv')

In [114]:
col_names = ['age', 'year', 'nodes', 'survival_status']
haberman.columns = col_names
col_names

['age', 'year', 'nodes', 'survival_status']

In [115]:
haberman.head()


age  year  nodes  survival_status
0   30    62      3                1
1   30    65      0                1
2   31    59      2                1
3   31    65      4                1
4   33    58     10                1

In [116]:
#Menentukan variabel independen
x = haberman.drop(["survival_status"], axis = 1)
x.head()

age  year  nodes
0   30    62      3
1   30    65      0
2   31    59      2
3   31    65      4
4   33    58     10

In [117]:
#Menentukan variabel dependen
y = haberman["survival_status"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: survival_status, dtype: int64

In [118]:
#Import package model selection dari SKLearn
from sklearn.model_selection import train_test_split

In [119]:
#Membagi data training dan data testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [120]:
#Mengaktifkan package dan syntax untuk mengubah skala data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)


In [121]:
#Mengaktifkan packages untuk klasifikasi dengan mengimport packages KNeighbors Classifierdari skLearn
from sklearn.neighbors import KNeighborsClassifier

In [122]:
#Mengaktifkan fungsi classifikasi untuk KNN
knn = KNeighborsClassifier (n_neighbors=4)

In [123]:
#Memasukan data training pada fungsi classifikasi untuk KNN
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [124]:
#Menentukan prediksi
y_pred = knn.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [125]:
#Menentukan probabilitas prediksi
knn.predict_proba(x_test)

array([[1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.75,

In [126]:
from sklearn.metrics import classification_report, confusion_matrix

In [127]:
#Menampilkan matriks hasil prediksi
print(confusion_matrix(y_test, y_pred))

[[40  3]
 [16  2]]


In [128]:
#Ketepatan hasil prediksi
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.71      0.93      0.81        43
           2       0.40      0.11      0.17        18

    accuracy                           0.69        61
   macro avg       0.56      0.52      0.49        61
weighted avg       0.62      0.69      0.62        61

