In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['heart.csv']


In [2]:
df = pd.read_csv(r'../input/heart.csv')

In [3]:
print(df)

     age  sex  cp  trestbps  chol   ...    oldpeak  slope  ca  thal  target
0     63    1   3       145   233   ...        2.3      0   0     1       1
1     37    1   2       130   250   ...        3.5      0   0     2       1
2     41    0   1       130   204   ...        1.4      2   0     2       1
3     56    1   1       120   236   ...        0.8      2   0     2       1
4     57    0   0       120   354   ...        0.6      2   0     2       1
5     57    1   0       140   192   ...        0.4      1   0     1       1
6     56    0   1       140   294   ...        1.3      1   0     2       1
7     44    1   1       120   263   ...        0.0      2   0     3       1
8     52    1   2       172   199   ...        0.5      2   0     3       1
9     57    1   2       150   168   ...        1.6      2   0     2       1
10    54    1   0       140   239   ...        1.2      2   0     2       1
11    48    0   2       130   275   ...        0.2      2   0     2       1
12    49    

In [4]:
dataset =  np.array(df.values)
np.random.shuffle(dataset)
print(dataset)

[[42.  1.  0. ...  0.  2.  1.]
 [51.  0.  2. ...  0.  2.  1.]
 [46.  0.  2. ...  0.  2.  1.]
 ...
 [61.  0.  0. ...  0.  2.  0.]
 [68.  1.  0. ...  2.  3.  0.]
 [67.  1.  2. ...  0.  3.  0.]]


In [5]:
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline  

In [6]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

**SVM CLASSIFICATION**

In [7]:
clf = svm.LinearSVC(penalty='l1',dual=False,tol=1e-3)
clf.fit(X_train, y_train) 

LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.001,
     verbose=0)

In [8]:
prediction = clf.predict(X_test)
print(accuracy_score(y_test, prediction))

0.8289473684210527


**DECISION TREE CLASSIFIER**

In [9]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [10]:
prediction = clf.predict(X_test)
print(accuracy_score(y_test, prediction))

0.8157894736842105


**KNN CLASSIFICATION**

In [11]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X_train,y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [12]:
prediction = neigh.predict(X_test)
print(accuracy_score(y_test, prediction))

0.618421052631579


**GAUSSIAN NAIVE BAYES**

In [13]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [14]:
y_pred = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.8289473684210527
