In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
pd.set_option("display.max_columns",500)

In [3]:
data_final=pd.read_csv("../input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
data=data_final.copy()
data["TotalCharges"]=pd.to_numeric(data["TotalCharges"], errors='coerce')
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7032 non-null float64
Churn               7043 non-null object
dtypes: float64(2), int64(2), ob

SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [5]:
data.describe(include="O")
data.isnull().sum()
data["TotalCharges"].describe()
data["TotalCharges"].fillna(1397.4750,inplace=True)
data.columns


Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [6]:
data=data.drop(["customerID"],axis=1)

In [7]:
data["Churn"].value_counts()
data.corr()

SeniorCitizen    tenure  MonthlyCharges  TotalCharges
SeniorCitizen        1.000000  0.016567        0.220173      0.102652
tenure               0.016567  1.000000        0.247900      0.825464
MonthlyCharges       0.220173  0.247900        1.000000      0.650864
TotalCharges         0.102652  0.825464        0.650864      1.000000

In [8]:
data2=pd.get_dummies(data,drop_first=True)
data2.columns
colmn=list(data2.columns)
feature= list(set(colmn)-set(["Churn_Yes"])) 
print(feature)
y=data2["Churn_Yes"].values 
print(y)

x=data2[feature].values
print(x)

['Partner_Yes', 'StreamingTV_Yes', 'Contract_One year', 'PaperlessBilling_Yes', 'InternetService_Fiber optic', 'TechSupport_Yes', 'PaymentMethod_Electronic check', 'Dependents_Yes', 'SeniorCitizen', 'Contract_Two year', 'MultipleLines_Yes', 'PhoneService_Yes', 'MonthlyCharges', 'tenure', 'StreamingTV_No internet service', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'InternetService_No', 'DeviceProtection_Yes', 'MultipleLines_No phone service', 'gender_Male', 'TotalCharges', 'PaymentMethod_Mailed check', 'OnlineBackup_No internet service', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'OnlineBackup_Yes', 'TechSupport_No internet service', 'DeviceProtection_No internet service', 'PaymentMethod_Credit card (automatic)']
[0 0 1 ... 0 1 0]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [9]:
from  sklearn.preprocessing import StandardScaler
sn= StandardScaler();
x=sn.fit_transform(x)

In [10]:
train_x,test_x,train_y,text_y=train_test_split(x,y, test_size=0.3 ,random_state=None)
logistic=LogisticRegression() 
logistic.fit(train_x,train_y) 

p=logistic.predict(test_x) 

confusion_matrix=confusion_matrix(text_y,p)
print(confusion_matrix)
acc=accuracy_score(text_y,p)
print(acc)
data2.describe()


[[1375  178]
 [ 229  331]]
0.807382867960246


/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


SeniorCitizen       tenure  MonthlyCharges  TotalCharges  gender_Male  \
count    7043.000000  7043.000000     7043.000000   7043.000000  7043.000000   
mean        0.162147    32.371149       64.761692   2281.916928     0.504756   
std         0.368612    24.559481       30.090047   2265.270398     0.500013   
min         0.000000     0.000000       18.250000     18.800000     0.000000   
25%         0.000000     9.000000       35.500000    402.225000     0.000000   
50%         0.000000    29.000000       70.350000   1397.475000     1.000000   
75%         0.000000    55.000000       89.850000   3786.600000     1.000000   
max         1.000000    72.000000      118.750000   8684.800000     1.000000   

       Partner_Yes  Dependents_Yes  PhoneService_Yes  \
count  7043.000000     7043.000000       7043.000000   
mean      0.483033        0.299588          0.903166   
std       0.499748        0.458110          0.295752   
min       0.000000        0.000000          0.000000   
25%       0.000000        0.000000          1.000000   
50%       0.000000        0.000000          1.000000   
75%       1.000000        1.000000          1.000000   
max       1.000000        1.000000          1.000000   

       MultipleLines_No phone service  MultipleLines_Yes  \
count                     7043.000000        7043.000000   
mean                         0.096834           0.421837   
std                          0.295752           0.493888   
min                          0.000000           0.000000   
25%                          0.000000           0.000000   
50%                          0.000000           0.000000   
75%                          0.000000           1.000000   
max                          1.000000           1.000000   

       InternetService_Fiber optic  InternetService_No  \
count                  7043.000000         7043.000000   
mean                      0.439585            0.216669   
std                       0.496372            0.412004   
min                       0.000000            0.000000   
25%                       0.000000            0.000000   
50%                       0.000000            0.000000   
75%                       1.000000            0.000000   
max                       1.000000            1.000000   

       OnlineSecurity_No internet service  OnlineSecurity_Yes  \
count                         7043.000000         7043.000000   
mean                             0.216669            0.286668   
std                              0.412004            0.452237   
min                              0.000000            0.000000   
25%                              0.000000            0.000000   
50%                              0.000000            0.000000   
75%                              0.000000            1.000000   
max                              1.000000            1.000000   

       OnlineBackup_No internet service  OnlineBackup_Yes  \
count                       7043.000000       7043.000000   
mean                           0.216669          0.344881   
std                            0.412004          0.475363   
min                            0.000000          0.000000   
25%                            0.000000          0.000000   
50%                            0.000000          0.000000   
75%                            0.000000          1.000000   
max                            1.000000          1.000000   

       DeviceProtection_No internet service  DeviceProtection_Yes  \
count                           7043.000000           7043.000000   
mean                               0.216669              0.343888   
std                                0.412004              0.475038   
min                                0.000000              0.000000   
25%                                0.000000              0.000000   
50%                                0.000000              0.000000   
75%                                0.000000              1.000000   
max                          

In [11]:

from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
for i in range(1,30):
 Kn= KNeighborsClassifier(n_neighbors=i)
 Kn.fit(train_x,train_y)

 p=Kn.predict(test_x)
 acc=accuracy_score(text_y,p)
 print(acc)
 print(i)



0.7127307146237577
1
0.7534311405584477
2
0.7415996213913867
3
0.7695220066256507
4
0.7557974443918599
5
0.7685754850922859
6
0.7761476573592049
7
0.7756743965925225
8
0.7737813535257927
9
0.779460482725982
10
0.7766209181258874
11
0.7860861334595362
12
0.7799337434926644
13
0.7860861334595362
14
0.7875059157595835
15
0.7893989588263133
16
0.7889256980596309
17
0.7936583057264552
18
0.7903454803596782
19
0.7889256980596309
20
0.7927117841930904
21
0.792238523426408
22
0.792238523426408
23
0.7908187411263606
24
0.791292001893043
25
0.7889256980596309
26
0.791292001893043
27
0.7903454803596782
28
0.792238523426408
29
