In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['Breast_cancer_data.csv']


In [2]:
breast_cancer=pd.read_csv('../input/Breast_cancer_data.csv')

In [3]:
breast_cancer.tail()
x=breast_cancer.iloc[:,0:5]
y=breast_cancer.iloc[:,5:]

In [4]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(max_features=3,criterion="entropy")

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.20,random_state=1999)

In [6]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=3, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [7]:
ypr=dtc.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_test,ypr))
print(confusion_matrix(y_test,ypr))

0.9298245614035088
[[40  4]
 [ 4 66]]


In [8]:
dtc.tree_.compute_feature_importances()

array([0.06045389, 0.12839612, 0.05919418, 0.6189427 , 0.1330131 ])

Last 3 feature is the most important in information theory entropy

In [9]:
breast_cancer.tail()

mean_radius  mean_texture    ...      mean_smoothness  diagnosis
564        21.56         22.39    ...              0.11100          0
565        20.13         28.25    ...              0.09780          0
566        16.60         28.08    ...              0.08455          0
567        20.60         29.33    ...              0.11780          0
568         7.76         24.54    ...              0.05263          1

[5 rows x 6 columns]

In [10]:
reducted=breast_cancer.iloc[:,2:5]
del reducted["mean_area"]

In [11]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)
ypr=svm.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_test,ypr))
print(confusion_matrix(y_test,ypr))

0.6403508771929824
[[ 4 40]
 [ 1 69]]


/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [12]:
x_train, x_test, y_train, y_test=train_test_split(reducted,y,test_size=0.20,random_state=1999)
svm=SVC()
svm.fit(x_train,y_train)
ypr=svm.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(accuracy_score(y_test,ypr))
print(confusion_matrix(y_test,ypr))

0.868421052631579
[[33 11]
 [ 4 66]]


/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Boost accuracy to %66 to %86 with only reduced dimensions. 