In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mobile-price-classification/train.csv
/kaggle/input/mobile-price-classification/test.csv


# Importing the libraries

In [2]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [3]:

train = pd.read_csv('../input/mobile-price-classification/train.csv')
test = pd.read_csv('../input/mobile-price-classification/train.csv')

X_train = train.drop(["price_range"],axis=1)
y_train = train["price_range"]

In [4]:
print(train.columns)
print(train.head())



Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')
   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7

In [5]:
print(test.columns)
print(test.head())

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')
   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7

# Analyzing the data

In [6]:
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [7]:
#buliding the optimal data using automatic backward elimnation
import statsmodels.api as sm
SL = 0.05
X_train_arr=X_train.values
X_opt = X_train_arr[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]]
X=np.append(arr=np.ones((2000,1)).astype(int),values=X_train,axis=1)
regressor_ols=sm.OLS(endog=y_train,exog=X_opt).fit()

print(regressor_ols.summary())
li=[]
def backwardElimination(x, sl):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.OLS(y_train, x).fit()
        maxVar = max(regressor_OLS.pvalues)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j] == maxVar):
                    x = np.delete(x, j, 1)
                    li.append(j)
    regressor_OLS.summary()
    return x
X_Modeled = backwardElimination(X_opt, SL)
test=test.values
test=np.delete(test,5,1)
test=np.delete(test,6,1)
test=np.delete(test,12,1)

                                 OLS Regression Results                                
Dep. Variable:            price_range   R-squared (uncentered):                   0.961
Model:                            OLS   Adj. R-squared (uncentered):              0.961
Method:                 Least Squares   F-statistic:                              2463.
Date:                Fri, 17 Jul 2020   Prob (F-statistic):                        0.00
Time:                        06:25:29   Log-Likelihood:                         -837.39
No. Observations:                2000   AIC:                                      1715.
Df Residuals:                    1980   BIC:                                      1827.
Df Model:                          20                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [8]:
len(X_Modeled[0])

17

In [9]:
#Applying feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_Modeled= sc.fit_transform(X_Modeled)
test = sc.fit_transform(test)

In [10]:
len(test[0])

18

# Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_Modeled, y_train, test_size = 0.3, random_state = 0)

# Fitting Kernel SVM to the Training set

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train1, y_train1)

SVC(random_state=0)

In [13]:
# Predicting the Test set results
y_pred_SVC= classifier.predict(X_test1)

In [14]:
#calculating accuracy
acc_SVC= round(classifier.score(X_train1,y_train1) * 100, 2)
print(acc_SVC)

97.93


In [15]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_SVC= confusion_matrix(y_test1, y_pred_SVC)
print(cm_SVC)

[[142   9   0   0]
 [ 12 111  12   0]
 [  0  16 129   6]
 [  0   0  16 147]]


# Fitting logistic regression to the training set

In [16]:
import sklearn

In [17]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train1,y_train1)

LogisticRegression(random_state=0)

In [18]:
# Predicting the Test set results
y_pred_logistic= classifier.predict(X_test1)

In [19]:
#calculating accuracy
acc_logistic= round(classifier.score(X_train1,y_train1) * 100, 2)
print(acc_SVC)

97.93


In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_logistic= confusion_matrix(y_test1, y_pred_logistic)
print(cm_logistic)

[[149   2   0   0]
 [  7 125   3   0]
 [  0   6 141   4]
 [  0   0   1 162]]


# Fitting the knn_calssifier to the training set

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(X_train1,y_train1)

KNeighborsClassifier()

In [22]:
# Predicting the Test set results
y_pred_knn= classifier.predict(X_test1)

In [23]:
#calculating accuracy
acc_knn= round(classifier.score(X_train1,y_train1) * 100, 2)
print(acc_knn)

69.5


In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_knn= confusion_matrix(y_test1, y_pred_knn)
print(cm_knn)

[[106  39   5   1]
 [ 45  67  15   8]
 [ 13  55  64  19]
 [  0  19  58  86]]


# Fitting Random forest classifier to the Training set

In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=0)
classifier.fit(X_train1,y_train1)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [26]:
# Predicting the Test set results
y_pred_random= classifier.predict(X_test1)

In [27]:
#calculating accuracy
acc_random= round(classifier.score(X_train1,y_train1) * 100, 2)
print(acc_random)

99.64


In [28]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_random= confusion_matrix(y_test1, y_pred_random)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test1,y_pred_random))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93       151
           1       0.76      0.77      0.76       135
           2       0.78      0.70      0.73       151
           3       0.89      0.91      0.90       163

    accuracy                           0.84       600
   macro avg       0.83      0.84      0.83       600
weighted avg       0.84      0.84      0.84       600

