In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/heart-disease-uci/heart.csv


In [2]:
df = pd.read_csv("../input/heart-disease-uci/heart.csv")
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0

In [3]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [4]:
df["age"].apply(lambda x: print(x))

63
37
41
56
57
57
56
44
52
57
54
48
49
64
58
50
58
66
43
69
59
44
42
61
40
71
59
51
65
53
41
65
44
54
51
46
54
54
65
65
51
48
45
53
39
52
44
47
53
53
51
66
62
44
63
52
48
45
34
57
71
54
52
41
58
35
51
45
44
62
54
51
29
51
43
55
51
59
52
58
41
45
60
52
42
67
68
46
54
58
48
57
52
54
45
53
62
52
43
53
42
59
63
42
50
68
69
45
50
50
64
57
64
43
55
37
41
56
46
46
64
59
41
54
39
34
47
67
52
74
54
49
42
41
41
49
60
62
57
64
51
43
42
67
76
70
44
60
44
42
66
71
64
66
39
58
47
35
58
56
56
55
41
38
38
67
67
62
63
53
56
48
58
58
60
40
60
64
43
57
55
65
61
58
50
44
60
54
50
41
51
58
54
60
60
59
46
67
62
65
44
60
58
68
62
52
59
60
49
59
57
61
39
61
56
43
62
63
65
48
63
55
65
56
54
70
62
35
59
64
47
57
55
64
70
51
58
60
77
35
70
59
64
57
56
48
56
66
54
69
51
43
62
67
59
45
58
50
62
38
66
52
53
63
54
66
55
49
54
56
46
61
67
58
47
52
58
57
58
61
42
52
59
40
61
46
59
57
57
55
61
58
58
67
44
63
63
59
57
45
68
57
57


0      None
1      None
2      None
3      None
4      None
       ... 
298    None
299    None
300    None
301    None
302    None
Name: age, Length: 303, dtype: object

In [5]:
X = df.drop('target', axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [6]:
y = df["target"]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


clf = RandomForestClassifier(random_state=42)
# clf = LogisticRegression(random_state=42)

In [9]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
        ('clf', clf)
])

In [10]:
pipeline.fit(X_train, y_train)

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
         steps=[('clf',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=42,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [11]:
pipeline.score(X_test, y_test)

0.8157894736842105

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = pipeline.predict(X_test)

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[29  6]
 [ 8 33]]
              precision    recall  f1-score   support

           0       0.78      0.83      0.81        35
           1       0.85      0.80      0.83        41

    accuracy                           0.82        76
   macro avg       0.81      0.82      0.82        76
weighted avg       0.82      0.82      0.82        76

0.8157894736842105


In [13]:
from sklearn.model_selection import GridSearchCV

hyperparameters = { 
                    'clf__n_estimators': np.arange(1, 60, 2),
                    'clf__max_depth': np.arange(1, 6, 1),
                    'clf__min_samples_split' : [2,3,4,5,6]
                  }
grd = GridSearchCV(pipeline, hyperparameters,  cv=5)
grd.fit(X_train, y_train)
grd.best_params_

/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'clf__max_depth': 3, 'clf__min_samples_split': 4, 'clf__n_estimators': 43}

In [14]:
pipeline = pipeline.set_params(**grd.best_params_)
pipeline.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('clf',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=3,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=4,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=43, n_jobs=None,
                                        oob_score=False, random_state=42,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [15]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [16]:
pipeline.predict([[18, 0, 3, 140, 200, 1, 0, 180, 1,3.2, 0,0,2]])

array([1])

In [17]:
y_pred = pipeline.predict(X_test)

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 



[[28  7]
 [ 5 36]]
              precision    recall  f1-score   support

           0       0.85      0.80      0.82        35
           1       0.84      0.88      0.86        41

    accuracy                           0.84        76
   macro avg       0.84      0.84      0.84        76
weighted avg       0.84      0.84      0.84        76

0.8421052631578947
