In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
df=pd.read_csv("../input/heart-disease-uci/heart.csv")

In [37]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [38]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [39]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [41]:
df.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

In [43]:
df.shape

(303, 14)

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', 1), df['target'], test_size = .2, random_state=25) 

In [45]:
X_train.shape

(242, 13)

In [46]:
y_test.shape

(61,)

In [47]:
X_train.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1     37    1   2       130   250    0        1      187      0      3.5   
142   42    0   2       120   209    0        1      173      0      0.0   
126   47    1   0       112   204    0        1      143      0      0.1   

     slope  ca  thal  
1        0   0     2  
142      1   0     2  
126      2   0     2

In [48]:
y_train.shape

(242,)

In [49]:
y_train.head()

1      1
142    1
126    1
37     1
275    0
Name: target, dtype: int64

In [50]:
from sklearn.ensemble import RandomForestClassifier 
classifier=RandomForestClassifier(n_estimators=20,random_state=30,max_features=13,max_depth=5)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features=13,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=30, verbose=0,
                       warm_start=False)

In [51]:
y_predict = classifier.predict(X_test)
y_pred_quant = classifier.predict_proba(X_test)[:, 1]

In [52]:
y_predict

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1])

In [53]:
y_pred_quant

array([0.68590667, 0.98828758, 0.75256646, 0.16213203, 0.99318954,
       0.74265002, 0.70977793, 0.06648284, 0.75003624, 0.89899041,
       0.07713203, 0.42909722, 0.00213203, 0.05083333, 0.96689563,
       0.98550556, 0.00213203, 0.58717027, 0.55434441, 0.46888889,
       0.98828758, 0.13960784, 0.71012856, 0.10294118, 0.39647296,
       0.00213203, 0.94932131, 0.69842982, 0.00213203, 0.90590701,
       0.05083333, 0.03546537, 0.53062957, 0.99318954, 0.47134694,
       0.66452175, 0.57617845, 0.92896097, 0.05213203, 0.34735299,
       0.62939583, 0.78668317, 0.05916667, 0.80095635, 0.55751895,
       0.80502704, 0.89539845, 0.81707004, 0.71235662, 0.99318954,
       0.00213203, 0.72994136, 0.12713203, 0.90092982, 0.87592982,
       0.00213203, 0.00213203, 0.45535562, 0.84408845, 0.45848007,
       0.98010435])

In [54]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
cm

array([[21,  8],
       [ 4, 28]])

In [55]:
print('Accuracy:{}'.format((21+28)/61))

Accuracy:0.8032786885245902
